### ISSUE TITLE
view component dont load

### ISSUE THREAD

**Issue by jjmontalban** [LaravelDaily/Laravel-Vue-First-CRUD#16]
Hi

I haver inserted one company directly in database. And route show company, but with any view!

https://prnt.sc/rcxd09

**Comment by jjmontalban** [comment]
Any idea?

**Comment by Daniyal-Javani** [comment]
Can you send me the error message that you got?

**Comment by jjmontalban** [comment]
Any error. Just dont show view 

https://prnt.sc/rcxscw

**Comment by jjmontalban** [comment]
The route is **http://localhost/laravue/public/api/v1/companies**

Only show a json with companies. But I dont know if css or any file is not linked. Dont appear any error

**Comment by Daniyal-Javani** [comment]
Look, there is no error in your screenshots, this is output of the api and that's fine.
You must check the Vue routes, it must be like the following link
http://localhost/laravue/public/companies

**Comment by jjmontalban** [comment]
Tahnks for your help. But I dont know why, the view dont show in these route:

https://prnt.sc/rcy2ac

Only show

https://prnt.sc/rcy2p2

**Comment by Daniyal-Javani** [comment]
Sorry my mistake, it's here
/admin/companies#/

probably this is yours
http://localhost/laravue/public/admin/companies#/

BTW, that's because of the prefix in route group
`'prefix' => 'admin'`

**Comment by jjmontalban** [comment]
> Sorry my mistake, it's here
> /admin/companies#/
> 
> probably this is yours
> http://localhost/laravue/public/admin/companies#/
> 
> BTW, that's because of the prefix in route group
> `'prefix' => 'admin'`

Great! Thanks a lot!
